name: HCPI Hourly
on:
  schedule:
    - cron: "5 * * * *"   # at minute 5 every hour (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run master runner
        env:
          HCPI_DATABASE_URL: ${{ secrets.HCPI_DATABASE_URL }}
        run: |
          python master_runner.py --cron --db "${HCPI_DATABASE_URL}" --verbose
      - name: Publish artifacts (JSON)
        if: always()
        run: |
          mkdir -p public/hcpi
          # assuming save_hcpi_results writes into ./docs or a known folder; copy them:
          find . -name "hcpi_*.json" -maxdepth 2 -print -exec cp {} public/hcpi/ \;
      - name: Deploy to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy
        uses: actions/deploy-pages@v4
