name: Forward Compute Index — Hourly Build & Deploy

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: false

env:
  PYTHON_VERSION: "3.12"
  COMMIT_DATA: 'false'

jobs:
  build-and-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run scrape + index pipeline
        continue-on-error: true
        env:
          HCPI_DATABASE_URL: ${{ secrets.HCPI_DATABASE_URL }}
        run: |
          python master_runner.py --cron --db "${HCPI_DATABASE_URL:-sqlite:///hcpi.db}" || echo "Scraping had issues, continuing"
          
      - name: Commit generated data to repository
        if: env.COMMIT_DATA == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            data/derived/*.csv
            data/history/*.csv
            hcpi/*.json
            hcpi/*history*.csv
          message: "ci: update data snapshots [skip ci]"
          author_name: github-actions
          author_email: actions@github.com
          
      - name: Prepare static site (public/)
        run: |
          mkdir -p public public/data/derived public/data/history public/hcpi
          
          if [ -f docs/index.html ]; then
            cp -f docs/index.html public/index.html
          elif [ -f index.html ]; then
            cp -f index.html public/index.html
          else
            echo '<!doctype html><meta charset="utf-8"><title>Forward Compute Index</title><body style="font:14px system-ui;padding:24px;color:#e7edf3;background:#0f1216"><h1>Forward Compute Index</h1><p>No dashboard found. Add <code>docs/index.html</code> to the repo.</p></body>' > public/index.html
          fi
          
          # Copy files with verification
          cp -v data/derived/*.csv public/data/derived/ || true
          cp -v data/history/*.csv public/data/history/ || true
          cp -v hcpi/*.json public/hcpi/ || true
          cp -v hcpi/*history*.csv public/hcpi/ || true
          
          echo "==== Verifying CSV line count ===="
          wc -l data/derived/provider_scores_latest.csv
          wc -l public/data/derived/provider_scores_latest.csv
          
          echo "==== public/ tree ===="
          find public -maxdepth 3 -type f -print

  deploy:
    needs: build-and-bundle
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

