# .github/workflows/index_hourly.yml
name: Price-IQ / HCPI — Hourly

on:
  schedule:
    - cron: "5 * * * *"  # every hour at minute 5
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # optional: playwright if your scrapers need it
          # pip install playwright
          # python -m playwright install --with-deps chromium

      - name: Run HCPI master runner
        env:
          HCPI_DATABASE_URL: ${{ secrets.HCPI_DATABASE_URL }}
        run: |
          python master_runner.py --cron --db sqlite:///hcpi.db

      - name: Prepare static site
        run: |
          mkdir -p public/hcpi
          mkdir -p public/data/derived
          cp docs/index.html public/index.html || true
          cp -r data/derived/*.csv public/data/derived/ || true
          cp -r hcpi/*.json public/hcpi/ || true
          echo '{"status":"ok","timestamp":"'$(date -u +%FT%TZ)'"}' > public/health.json

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build-and-deploy
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

